# Generated by Django 6.0.2 on 2026-05-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('grocery', 'Grocery'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('home', 'Home')], default='grocery', max_length=50),
        ),
    ]
