# Generated by Django 6.0.6 on 2026-06-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_latitude_delivery_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='longitude',
        ),
    ]
