# Generated by Django 6.0.6 on 2026-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('not_available', 'Not Available'), ('available', 'Available'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='not_available', max_length=30),
        ),
    ]
