# Generated by Django 6.0.6 on 2026-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivered_at_order_return_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='none', max_length=20),
        ),
    ]
