# Generated by Django 6.0.6 on 2026-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivered_at_alter_order_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
