# Generated by Django 6.0.6 on 2026-06-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_phone'),
        ('notifications', '0002_remove_notification_customer_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
